/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExportRouteImport } from './routes/export'
import { Route as ReconstructRouteImport } from './routes/reconstruct'
import { Route as RefineRouteImport } from './routes/refine'
import { Route as ScenesRouteImport } from './routes/scenes'
import { Route as TextureRouteImport } from './routes/texture'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconstructRoute = ReconstructRouteImport.update({
  id: '/reconstruct',
  path: '/reconstruct',
  getParentRoute: () => rootRouteImport,
} as any)
const RefineRoute = RefineRouteImport.update({
  id: '/refine',
  path: '/refine',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenesRoute = ScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const TextureRoute = TextureRouteImport.update({
  id: '/texture',
  path: '/texture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/reconstruct': typeof ReconstructRoute
  '/refine': typeof RefineRoute
  '/scenes': typeof ScenesRoute
  '/texture': typeof TextureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/reconstruct': typeof ReconstructRoute
  '/refine': typeof RefineRoute
  '/scenes': typeof ScenesRoute
  '/texture': typeof TextureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/reconstruct': typeof ReconstructRoute
  '/refine': typeof RefineRoute
  '/scenes': typeof ScenesRoute
  '/texture': typeof TextureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/export' | '/reconstruct' | '/refine' | '/scenes' | '/texture'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/export' | '/reconstruct' | '/refine' | '/scenes' | '/texture'
  id:
    | '__root__'
    | '/'
    | '/export'
    | '/reconstruct'
    | '/refine'
    | '/scenes'
    | '/texture'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExportRoute: typeof ExportRoute
  ReconstructRoute: typeof ReconstructRoute
  RefineRoute: typeof RefineRoute
  ScenesRoute: typeof ScenesRoute
  TextureRoute: typeof TextureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconstruct': {
      id: '/reconstruct'
      path: '/reconstruct'
      fullPath: '/reconstruct'
      preLoaderRoute: typeof ReconstructRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refine': {
      id: '/refine'
      path: '/refine'
      fullPath: '/refine'
      preLoaderRoute: typeof RefineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenes': {
      id: '/scenes'
      path: '/scenes'
      fullPath: '/scenes'
      preLoaderRoute: typeof ScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texture': {
      id: '/texture'
      path: '/texture'
      fullPath: '/texture'
      preLoaderRoute: typeof TextureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExportRoute: ExportRoute,
  ReconstructRoute: ReconstructRoute,
  RefineRoute: RefineRoute,
  ScenesRoute: ScenesRoute,
  TextureRoute: TextureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
