/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as ExportRouteImport } from './routes/export'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReconstructRouteImport } from './routes/reconstruct'
import { Route as RefineRouteImport } from './routes/refine'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScenesRouteImport } from './routes/scenes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TextureRouteImport } from './routes/texture'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconstructRoute = ReconstructRouteImport.update({
  id: '/reconstruct',
  path: '/reconstruct',
  getParentRoute: () => rootRouteImport,
} as any)
const RefineRoute = RefineRouteImport.update({
  id: '/refine',
  path: '/refine',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenesRoute = ScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TextureRoute = TextureRouteImport.update({
  id: '/texture',
  path: '/texture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/explorer': typeof ExplorerRoute
  '/export': typeof ExportRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/reconstruct': typeof ReconstructRoute
  '/refine': typeof RefineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scenes': typeof ScenesRoute
  '/settings': typeof SettingsRoute
  '/texture': typeof TextureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/explorer': typeof ExplorerRoute
  '/export': typeof ExportRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/reconstruct': typeof ReconstructRoute
  '/refine': typeof RefineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scenes': typeof ScenesRoute
  '/settings': typeof SettingsRoute
  '/texture': typeof TextureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/explorer': typeof ExplorerRoute
  '/export': typeof ExportRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/reconstruct': typeof ReconstructRoute
  '/refine': typeof RefineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scenes': typeof ScenesRoute
  '/settings': typeof SettingsRoute
  '/texture': typeof TextureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/explorer'
    | '/export'
    | '/history'
    | '/login'
    | '/reconstruct'
    | '/refine'
    | '/reset-password'
    | '/scenes'
    | '/settings'
    | '/texture'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/explorer'
    | '/export'
    | '/history'
    | '/login'
    | '/reconstruct'
    | '/refine'
    | '/reset-password'
    | '/scenes'
    | '/settings'
    | '/texture'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/explorer'
    | '/export'
    | '/history'
    | '/login'
    | '/reconstruct'
    | '/refine'
    | '/reset-password'
    | '/scenes'
    | '/settings'
    | '/texture'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRoute
  ExplorerRoute: typeof ExplorerRoute
  ExportRoute: typeof ExportRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ReconstructRoute: typeof ReconstructRoute
  RefineRoute: typeof RefineRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScenesRoute: typeof ScenesRoute
  SettingsRoute: typeof SettingsRoute
  TextureRoute: typeof TextureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconstruct': {
      id: '/reconstruct'
      path: '/reconstruct'
      fullPath: '/reconstruct'
      preLoaderRoute: typeof ReconstructRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refine': {
      id: '/refine'
      path: '/refine'
      fullPath: '/refine'
      preLoaderRoute: typeof RefineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenes': {
      id: '/scenes'
      path: '/scenes'
      fullPath: '/scenes'
      preLoaderRoute: typeof ScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texture': {
      id: '/texture'
      path: '/texture'
      fullPath: '/texture'
      preLoaderRoute: typeof TextureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRoute,
  ExplorerRoute: ExplorerRoute,
  ExportRoute: ExportRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ReconstructRoute: ReconstructRoute,
  RefineRoute: RefineRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScenesRoute: ScenesRoute,
  SettingsRoute: SettingsRoute,
  TextureRoute: TextureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
