/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReconstructRouteImport } from './routes/reconstruct'
import { Route as RefineRouteImport } from './routes/refine'
import { Route as TextureRouteImport } from './routes/texture'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconstructRoute = ReconstructRouteImport.update({
  id: '/reconstruct',
  path: '/reconstruct',
  getParentRoute: () => rootRouteImport,
} as any)
const RefineRoute = RefineRouteImport.update({
  id: '/refine',
  path: '/refine',
  getParentRoute: () => rootRouteImport,
} as any)
const TextureRoute = TextureRouteImport.update({
  id: '/texture',
  path: '/texture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reconstruct': typeof ReconstructRoute
  '/refine': typeof RefineRoute
  '/texture': typeof TextureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reconstruct': typeof ReconstructRoute
  '/refine': typeof RefineRoute
  '/texture': typeof TextureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reconstruct': typeof ReconstructRoute
  '/refine': typeof RefineRoute
  '/texture': typeof TextureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reconstruct' | '/refine' | '/texture'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reconstruct' | '/refine' | '/texture'
  id: '__root__' | '/' | '/reconstruct' | '/refine' | '/texture'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReconstructRoute: typeof ReconstructRoute
  RefineRoute: typeof RefineRoute
  TextureRoute: typeof TextureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconstruct': {
      id: '/reconstruct'
      path: '/reconstruct'
      fullPath: '/reconstruct'
      preLoaderRoute: typeof ReconstructRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refine': {
      id: '/refine'
      path: '/refine'
      fullPath: '/refine'
      preLoaderRoute: typeof RefineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texture': {
      id: '/texture'
      path: '/texture'
      fullPath: '/texture'
      preLoaderRoute: typeof TextureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReconstructRoute: ReconstructRoute,
  RefineRoute: RefineRoute,
  TextureRoute: TextureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
